name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1=h57928b3_3
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.25.2=pyhcf101f3_0
  - aiodns=3.0.0=pyhd8ed1ab_0
  - aiofiles=25.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h582051c_0
  - aiohttp-client-cache=0.14.2=pyhd8ed1ab_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aiosqlite=0.21.0=pyhaa4b35c_0
  - aniso8601=10.0.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - anywidget=0.9.21=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h3485c13_2
  - arrow=1.4.0=pyhcf101f3_0
  - arrow-cpp=21.0.0=h6358905_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - async-retriever=0.19.3=pyha770c72_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.6=hdc32d89_1
  - aws-c-http=0.10.4=hce07812_1
  - aws-c-io=0.21.4=h20b9e97_1
  - aws-c-mqtt=0.13.3=hc9a9668_4
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backoff=2.2.1=pyhd8ed1ab_1
  - bash_kernel=0.7.2=py_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=h85f69ea_0
  - bokeh=3.8.1=pyhd8ed1ab_0
  - botocore=1.40.70=pyhd8ed1ab_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - bqplot=0.12.45=pyhe01879c_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py311h12c1d0e_9
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.4=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachelib=0.13.0=pyhd8ed1ab_1
  - cachetools=6.2.2=pyhd8ed1ab_0
  - cairo=1.18.0=h91e5215_2
  - cattrs=25.3.0=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - cfitsio=3.470=h0af3d06_7
  - cftime=1.6.4=py311h17033d2_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - choreographer=1.2.1=pyhcf101f3_0
  - click=8.3.1=pyh7428d3b_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - color-operations=0.2.0=py311h17033d2_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - colour=0.1.5=pyhd8ed1ab_2
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cryptography=46.0.3=py311habbc9f9_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py311h3485c13_1
  - dask=2025.11.0=pyhcf101f3_0
  - dask-core=2025.11.0=pyhcf101f3_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2025.11.0=pyhcf101f3_0
  - distro=1.9.0=pyhd8ed1ab_1
  - docutils=0.22.3=pyhd8ed1ab_0
  - duckdb-engine=0.15.0=pyh885dcc9_0
  - earthaccess=0.15.1=pyhcf101f3_0
  - earthengine-api=1.7.1=pyhd8ed1ab_0
  - eerepr=0.1.2=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - eval-type-backport=0.3.0=pyhd8ed1ab_0
  - eval_type_backport=0.3.0=pyha770c72_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - ffmpeg=6.1.2=gpl_h9cf63cc_102
  - ffmpeg-python=0.2.0=pyhff2d567_1
  - filelock=3.20.0=pyhd8ed1ab_0
  - fiona=1.10.1=py311h5da7b33_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-caching=2.3.1=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - flask-restx=1.3.0=pyhd8ed1ab_1
  - fmt=9.1.0=h181d51b_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=h8276f4a_0
  - fribidi=1.0.16=hfd05255_0
  - frozenlist=1.7.0=py311hdf60d3a_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdal=3.6.2=py311hcb0bb8f_10
  - gdown=5.2.0=pyhd8ed1ab_1
  - geeadd=0.5.6=pyhd8ed1ab_0
  - geedim=2.0.0=pyhd8ed1ab_0
  - geemap=0.36.6=pyhd8ed1ab_0
  - geocoder=1.38.1=pyhd8ed1ab_2
  - geojson=3.2.0=pyhd8ed1ab_0
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.10.6=hd4c2148_0
  - geotiff=1.7.0=hbf7d8e7_4
  - gflags=2.2.2=he0c23c2_1005
  - gl2ps=1.4.2=had7236b_1
  - glog=0.5.0=h4797de2_0
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-cloud-core=2.5.0=pyhd8ed1ab_0
  - google-cloud-storage=3.6.0=pyhcf101f3_0
  - google-crc32c=1.7.1=py311h178015e_1
  - google-resumable-media=2.8.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - greenlet=3.2.4=py311h3e6a449_1
  - grpcio=1.71.0=py311hbb1fe6b_0
  - grpcio-status=1.71.0=pyhd8ed1ab_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=py311he283ef2_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.14.5=ha36df97_2
  - holoviews=1.22.0=pyhd8ed1ab_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - humanize=4.14.0=pyhd8ed1ab_0
  - hvplot=0.12.1=pyhd8ed1ab_0
  - hypercoast=0.16.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.11=pyhd8ed1ab_0
  - impi_rt=2021.16.0=h57928b3_439
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipyevents=2.0.4=pyhbbac1ac_0
  - ipyfilechooser=0.6.0=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipyleaflet=0.20.0=pyhd8ed1ab_0
  - ipysheet=0.7.0=pyhd8ed1ab_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipytree=0.2.2=pyhd8ed1ab_1
  - ipyvue=1.11.2=pyhd8ed1ab_0
  - ipyvuetify=1.11.3=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - json5=0.12.1=pyhd8ed1ab_0
  - jsoncpp=1.9.4=h2d74725_3
  - jsonpointer=3.0.0=py311h1ea47a8_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupysql=0.11.1=pyhd8ed1ab_0
  - jupysql-plugin=0.4.5=pyhd8ed1ab_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter-server-proxy=4.4.0=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_leaflet=0.20.0=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jupytext=1.18.1=pyh80e38bb_0
  - kealib=1.5.0=h6c4040a_2
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=h885b0b7_4
  - lark=1.3.1=pyhd8ed1ab_0
  - laspy=2.6.1=py311hbad1e7f_1
  - lazrs-python=0.8.0=py311hf51aa87_1
  - lcms2=2.16=h62be587_1
  - leafmap=0.57.9=pyhd8ed1ab_0
  - legacy-cgi=2.6.4=pyhcf101f3_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libaec=1.1.4=h20038f6_0
  - libavif=1.1.1=h4e96d62_1
  - libavif16=1.1.1=h4e96d62_1
  - libblas=3.9.0=35_h5709861_mkl
  - libboost=1.88.0=h3d2b97d_0
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_12
  - libgdal=3.6.2=hdf1f3d4_10
  - libglib=2.84.2=h405b238_0
  - libgomp=15.2.0=h8ee18e1_12
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkml=1.3.0=h68a222c_1022
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libnetcdf=4.9.3=h0c3980a_0
  - libogg=1.3.5=h2466b09_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.51=h7351971_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=he9d8c4a_0
  - libre2-11=2024.07.02=hd248061_3
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=h6715bb4_2
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h2addb87_0
  - libtheora=1.1.1=hc70643c_1006
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.3.1=h02ab6af_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - llvm-openmp=21.1.6=h4fa8253_0
  - localtileserver=0.10.6=pyhd8ed1ab_0
  - locket=1.0.0=pyhd8ed1ab_0
  - logistro=2.0.1=pyhcf101f3_0
  - logzero=1.7.0=py311h1ea47a8_7
  - lxml=6.0.2=py311hea5fcc3_0
  - lz4=4.3.3=py311h8b5e962_1
  - lz4-c=1.9.4=hcfcfb64_0
  - m2r2=0.3.1=pyhd8ed1ab_0
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - maplibre=0.3.5=pyhd8ed1ab_0
  - mapwidget=0.2.0=pyhd8ed1ab_0
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.6=hb638d1e_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2024.2.2=h57928b3_16
  - monotonic=1.6=pyhd8ed1ab_0
  - morecantile=6.2.0=pyhd8ed1ab_0
  - mpi=1.0=impi
  - mpi4py=4.1.1=py311h58c7454_101
  - msgpack-python=1.1.2=py311h3fd045d_1
  - multidict=6.6.3=py311h3f79411_0
  - multimethod=2.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mystmd=1.6.6=pyhcf101f3_0
  - narwhals=2.12.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hc388f54_1
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbconvert-pandoc=7.16.6=h7d6f222_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=py311hd3a5b52_2
  - networkx=3.6=pyhcf101f3_0
  - nlohmann_json=3.12.0=h5112557_1
  - nodejs=24.9.0=he453025_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.14.1=mkl_py311hcc47716_1
  - numpy=2.3.5=py311h80b3fa1_0
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py311h4d8bf61_2
  - openssl=3.0.18=h543e019_0
  - opera-utils=0.19.0=pyhd8ed1ab_0
  - orc=2.2.0=hf43e1a1_0
  - orjson=3.11.4=py311hf51aa87_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - owslib=0.35.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pandoc=3.8.2.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.8.3=pyhd8ed1ab_0
  - param=2.3.0=pyhc455866_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.42=h17e33f8_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py311h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - planetary-computer=1.0.0=pyhd8ed1ab_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - ploomber-core=0.2.27=pyhd8ed1ab_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pmtiles=3.4.1=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - poppler=24.09.0=h10b5248_4
  - poppler-data=0.4.12=hd8ed1ab_0
  - posthog=7.0.1=pyhd8ed1ab_0
  - pqdm=0.2.0=pyhd8ed1ab_1
  - prettytable=3.17.0=pyhd8ed1ab_0
  - proj=9.3.1=he13c7e8_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h5082efb_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=5.29.3=py311hda3d55a_0
  - pscript=0.7.7=pyhd8ed1ab_0
  - psutil=7.1.3=py311hf893f09_0
  - psygnal=0.15.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h0e40799_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py3dep=0.19.0=pyhd8ed1ab_0
  - pyarrow=21.0.0=py311ha5e6156_0
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycares=4.11.0=py311h3485c13_1
  - pycparser=2.22=pyh29332c3_1
  - pycrs=1.0.2=pyhd8ed1ab_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py311hf51aa87_1
  - pygeoogc=0.19.4=pyhd8ed1ab_0
  - pygeoutils=0.19.5=pyhd8ed1ab_0
  - pygis=0.10.1=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymdown-extensions=10.17.1=pyhd8ed1ab_0
  - pyntcloud=0.3.1=pyhd8ed1ab_1
  - pyogrio=0.10.0=py311he5c4563_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyperclip=1.11.0=pyh7428d3b_0
  - pyproj=3.6.1=py311h82130bc_5
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - pystac=1.14.1=pyhd8ed1ab_0
  - pystac-client=0.9.0=pyhd8ed1ab_0
  - pytest=9.0.1=pyhcf101f3_0
  - pytest-timeout=2.4.0=pyhd8ed1ab_0
  - python=3.11.14=h981015d_0
  - python-box=7.3.2=py311h3485c13_1
  - python-cmr=0.13.0=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-duckdb=1.4.2=py311h3e6a449_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-kaleido=1.2.0=pyhcf101f3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyvista=0.44.1=pyhd8ed1ab_0
  - pyviz_comms=3.0.6=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pywinpty=2.0.15=py311hda3d55a_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.7.3=hd088775_4
  - rasterio=1.4.3=py311he5c4563_0
  - ratelim=0.1.6=pyhd8ed1ab_3
  - rav1e=0.6.6=h975169c_2
  - re2=2024.07.02=haf4117d_3
  - reacton=1.9.1=pyhd8ed1ab_1
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-cache=1.2.1=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.4=pyhd8ed1ab_0
  - rio-cogeo=7.0.0=pyhd8ed1ab_0
  - rio-tiler=7.9.2=pyhd8ed1ab_0
  - rioxarray=0.19.0=pyhd8ed1ab_0
  - rpds-py=0.29.0=py311hf51aa87_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py311h3485c13_0
  - ruamel.yaml.clib=0.2.14=py311h3485c13_0
  - s3fs=2025.10.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scooby=0.11.0=pyhd8ed1ab_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - server-thread=0.3.0=pyhd8ed1ab_0
  - setuptools=80.9.0=py311haa95532_0
  - shapely=2.1.1=py311hbe77627_0
  - simpervisor=1.0.0=pyhd8ed1ab_1
  - simplejson=3.20.2=py311h3485c13_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - solara=1.54.0=pyhd8ed1ab_0
  - solara-server=1.54.0=pyhd8ed1ab_0
  - solara-ui=1.54.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlalchemy=2.0.44=py311h3485c13_0
  - sqlglot=28.0.0=pyhcf101f3_0
  - sqlite=3.51.0=hda9a48d_0
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - statsmodels=0.14.5=py311h17033d2_1
  - svt-av1=2.2.1=he0c23c2_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.13.0=hd094cb3_4
  - tblib=3.2.2=pyhcf101f3_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiledb=2.3.3=hd8964de_3
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_2
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py311h3485c13_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.3=pyh332efcf_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - typst=0.14.0=h77a83cd_0
  - tzdata=2025b=h04d1e81_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.11.0=py311h5dfdfe8_1
  - unicodedata2=17.0.0=py311h3485c13_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h5a68840_0
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - url-normalize=2.2.1=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h2bbff1b_1
  - utfcpp=4.0.8=h57928b3_0
  - uvicorn=0.38.0=pyh5737063_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - voila=0.5.11=pyhd8ed1ab_1
  - voila_topbar=0.1.1=pyh80e38bb_1
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - vtk=9.4.1=h61baa6d_3
  - vtk-base=9.4.1=py311h0e0f593_3
  - watchdog=6.0.0=py311h1ea47a8_2
  - watchfiles=1.1.1=py311h18438d6_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py311hf893f09_2
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py311haa95532_0
  - whitebox=2.3.6=pyhd8ed1ab_0
  - whiteboxgui=2.3.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py311h3485c13_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=2025.11.0=pyhcf101f3_0
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libx11=1.8.12=hf48077a_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py311h3f79411_0
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - lab==8.5
      - notebook==7.5.0
      - scipy==1.16.3
      - tinycss2==1.4.0
      - txt2tags==3.9
prefix: C:\Users\tania\miniconda3\envs\geo
